server.port=8080

spring.application.name=API-GATEWAY

# ==============================
# EUREKA CONFIG
# ==============================
eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.instance.hostname=localhost
eureka.instance.prefer-ip-address=false
eureka.instance.instance-id=api-gateway:8080
spring.main.web-application-type=reactive
jwt.secret=mysecretkeymysecretkeymysecretkey
# ==============================
# GATEWAY ROUTES
# ==============================
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedOrigins=http://localhost:3000
spring.cloud.gateway.globalcors.cors-configurations.[/*].allowedMethods=
spring.cloud.gateway.globalcors.cors-configurations.[/*].allowedHeaders=
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowCredentials=true
# AUTH SERVICE
spring.cloud.gateway.routes[0].id=auth-service
spring.cloud.gateway.routes[0].uri=lb://AUTH-SERVICE
spring.cloud.gateway.routes[0].predicates[0]=Path=/auth/**

# USER SERVICE
spring.cloud.gateway.routes[1].id=user-service
spring.cloud.gateway.routes[1].uri=lb://USER-SERVICE
spring.cloud.gateway.routes[1].predicates[0]=Path=/users/**

# COMPLAINT SERVICE
spring.cloud.gateway.routes[2].id=complaint-service
spring.cloud.gateway.routes[2].uri=lb://COMPLAINT-SERVICE
spring.cloud.gateway.routes[2].predicates[0]=Path=/complaints/**

# ADMIN SERVICE
spring.cloud.gateway.routes[3].id=admin-service
spring.cloud.gateway.routes[3].uri=lb://ADMIN-SERVICE
spring.cloud.gateway.routes[3].predicates[0]=Path=/admin/**

# NOTIFICATION SERVICE
spring.cloud.gateway.routes[4].id=notification-service
spring.cloud.gateway.routes[4].uri=lb://NOTIFICATION-SERVICE
spring.cloud.gateway.routes[4].predicates[0]=Path=/notifications/**